[package]
name = "dim-database"
version = "0.1.0"
authors = ["Valerian G. <valerian.garleanu@pm.me>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.2", features = ["sqlite", "postgres"] }
r2d2 = "0.8.5"
r2d2-diesel = "1.0.0"
serde = { version  = "*", features = ["derive"] }
serde_derive = "1.0.98"
serde_json = "1.0.40"
diesel_migrations = "1.4.0"
diesel_full_text_search = "1.0.1"
